Gemfile, Gemfile.lock
When I tried to run `bin/rails console` locally for the first time, I
received an error about readline. Based on this comment
(https://github.com/rails/rails/issues/26658#issuecomment-307238834)
I added rb-readline to the gem file, ran bundle install again, and it
worked fine.
=> Add rb-readline gem to development requirements

app/assets/stylesheets/2018/main.css.scss, app/views/shared/_button_to_get.haml, app/views/users/show.html.haml
We've had a couple reports of the "Add Adult Attendee" button not doing
anything. It's using kind of an unnecessarily complicated means
involving JS to act as a button that links to a URL with a query
string--just using CSS to make an anchor tag look like a button is
simpler, and should eliminate any possible issue with the button.
I've also fixed the issue with the attendee box bumping directly into
the buttons beneath it.
=> Rewrite `button_to_get` helper

app/assets/stylesheets/2018/main.css.scss, lib/name_inflector.rb, spec/models/name_inflector_spec.rb
The site's NameInflector was transforming "Nate Eagle, Jr." into "Nate
Eagle, jr.", which led to a user complaint. I added an array to deal
with suffixes that should be capitalized and added "jr." and "sr."...
perhaps someday we can add "esq."
=> Fix capitalization for juniors (and seniors)

app/forms/registration.rb, app/helpers/attendee_helper.rb, spec/forms/registration_spec.rb
When using radio buttons the name attribute must be the same for all
plans in the plan category. This causes the params for the plans with
radio buttons to differ from those with check boxes. I added a method to
covert the plan params using radio buttons to use the expected checkbox
format.
close #105
=> Change select box to radio button for single plan categories

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/exporters/players_xml_exporter.rb, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, config/routes.rb, spec/controllers/rpt/usopen_players_reports_controller_spec.rb
* Create a report listing all the attendees who have opted in to the
U.S. Open
* Fetch info from https://www.usgo.org/mm/tdlista.txt to get current
stats such as official AGA rating
* Cache that info so we don't fetch all that info unnecessarily
* Flag users who have self-promoted
* Create an XML file designed to be imported into OpenGotha
This closes #110.
=> Create U.S. Open Players Report & XML Import

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/controllers/years_controller.rb, app/exporters/players_xml_exporter.rb, app/helpers/attendee_helper.rb, app/models/attendee/who_is_coming.rb, app/models/attendee/who_is_coming.sql, app/views/plan_categories/_plan_table_common_cells.html.haml, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, app/views/shared/_plan_date_fields.haml, app/views/users/pay.html.haml, app/views/years/_form.html.haml, config/routes.rb, db/migrate/20180508025356_add_refund_policy_to_year.rb, db/schema.rb, spec/factories/attendees.rb, spec/models/attendee/who_is_coming_spec.rb
Our refund/cancellation policy was one of the first things a user asked
for this year when registration opened. Which makes sense! This is
something every year's Congress should be prompted to set, and should
always show on the "Make a Payment" page.
It also adds a new "policies" box of settings to the admin, which will
be a good place to add any always-relevant policy fields to help each
year's Congress kick things off.
=> Add a refund_policy field to years model

app/controllers/rpt/minor_agreements_reports_controller.rb, app/forms/registration.rb, app/views/registrations/_form.html.haml, app/views/reports/index.html.haml, app/views/rpt/minor_agreements_reports/show.html.haml, config/routes.rb, spec/controllers/registrations_controller_spec.rb, spec/controllers/rpt/minor_agreements_reports_controller_spec.rb
Closes #79.
I started to create a migration to add this checkbox, which has been
requested by our registrar and a previous registrar, only to discover
that it already existed. It looks like there used to be an issue with
the way the project originally protected admin-only attributes in the
registration form.
This restores these fields, then adds some new logic to the registration
controller to ensure that only admins can update these fields. @rcristal,
definitely let me know if you have any questions about how that new
logic works.
This also adds a (very simple) report to the `rpt` namespace to show a
list of minor attendees for whom we've got an agreement and those for
whom we don't.
* Adds a test to verify that admins can update admin-only fields in reg
* Adds a test of the new report …
=> Add `minor_agreement_received` checkbox for admin

app/controllers/content_categories_controller.rb, app/views/content_categories/_form.html.haml, app/views/content_categories/show.html.haml, app/views/contents/_form.html.haml, app/views/contents/show.html.haml, db/migrate/20180524165637_add_table_of_contents_to_content_category.rb
Some content categories--I'm looking at you, FAQ!--really need a nice
table of contents at the top to let people quickly scan all the items
and click particular ones that interest them.
This creates a new column attached to content_categories that turns on a
TOC and outputs it as a list of links at the top of the page in the
view.
There are no current tests for `content_categories` or `contents` -- it will probably be worth it to get some set up someday, but they're extremely simple and this is a very simple additional feature.
=> Add table of contents option to content categories

app/helpers/attendee_helper.rb, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/registrations/_plans.haml
There was a UI scenario that I overlooked in the recent change from check-boxes to radio buttons for single-value plans: when it's a non-mandatory plan, there needs to be a way for a user to select "none" if they click on a plan but change their mind.
=> Provide a "no selection" option for non-mandatory, single-value plans

app/controllers/contents_controller.rb, app/views/contents/_form.html.haml
* Use the `content_category_id` for new content
* Use the category_id from existing content for edit
=> Fix new content to choose correct default category

app/controllers/attendees_controller.rb, spec/controllers/attendees_controller_spec.rb
We had a report of a pro who'd been registered by a friend. They were
cancelled, but still showing up on the pros (vip) list.
=> Remove cancelled attendees from the pros list

app/assets/stylesheets/2018/main.css.scss, app/views/registrations/_plans.haml
* Add plan category names
* separate plan tables visually to provide more clarity
* Hide extended descriptions by default, allow them to be shown when a
user clicks "more details"
@rcristal This is a front-end-only PR--as per our last discussion, I'm going to push it to heroku.
=> Make registration form more readable

app/views/attendees/index.html.haml
Since this year's Congress (2019) is using a separate system for
registration, the dynamic "Who's Coming?" page isn't accurate. There's
work purportedly underway in syncing them, but we needed to put up
information in the meantime. This adds a static table generated
separately from a spreadhseet and comments out the page's normal dynamic
functionality.
=> Temporarily add static information to "Who's Coming"

app/assets/stylesheets/main.scss, app/assets/stylesheets/print.scss, app/controllers/api_controller.rb, app/controllers/registrations_controller.rb, app/views/2018/registrations/_player_info.html.haml, app/views/registrations/_activities.html.haml, app/views/registrations/_form.html.haml, app/views/registrations/_personal_info.html.haml, app/views/registrations/_plans.haml, app/views/registrations/_player_info.html.haml, app/views/registrations/aga_member_search.html.haml, app/views/users/invoice.html.haml, config/locales/en.yml, config/routes.rb, spec/features/attendee_form_spec.rb
Make adding an attendee easier by searching the AGA Members API for
their name or AGA ID and using the values there to pre-fill parts of
their Congress registration.
The new flow presents a starting screen after clicking "add attendee"
that displays only a search box for the API and a button for anyone
trying to register without being a member. (Many non-players and other
guests are attendees at a typical Congress.)
Once either a member is selected via the search or the not-a-member
button is clicked, the next page is the previous registration form, but
with as many values as I could find that were relevant filled in from
existing info.
Closes #192
=> Modify registration to get values from Members API

app/assets/javascripts/application.js, app/assets/javascripts/editable_texts.js, app/assets/stylesheets/editable_texts.scss, app/assets/stylesheets/main.scss, app/controllers/api_controller.rb, app/controllers/attendees_controller.rb, app/controllers/editable_texts_controller.rb, app/helpers/editable_texts_helper.rb, app/models/ability.rb, app/models/editable_text.rb, app/views/attendees/vip.html.haml, app/views/contacts/index.html.haml, app/views/content_categories/index.html.haml, app/views/editable_texts/index.html.haml, app/views/home/_logo_and_welcome.haml, config/routes.rb, db/migrate/20210506021835_create_editable_texts.rb, db/schema.rb, spec/rails_helper.rb, spec/requests/editable_texts_spec.rb
This new feature lets admins update the text for visible sections of the
website without needing to modify code in the site itself. It creates a
new admin section accessible via "Content" that lets admins write
content in Markdown that will be displayed in major sections of the
site, such as the logo and welcome on the homepage, the contact us page,
and the pros page.
We'll probably add other sections to this later on. We could also add
some easier ways for admins to directly edit text *from* where they
actually live rather than having to go to a specific admin page, but we
can add those later.
Closes #191
=> Add new "editable texts" feature for admins

app/controllers/api_controller.rb, app/services/pandanet/client.rb, app/services/pandanet/stats.rb, spec/requests/api_spec.rb, spec/services/pandanet/stats_spec.rb
There are a few things to talk about here.
The goal is to test the Pandanet `stats` feature, without an actual (fallible) network connection. Extracting a `::Pandanet::Client` class gives the controller something to mock. This is the more important commit. Then, extracting the `Stats` class enables us to test the parsing.
I ran into an issue re: Pandanet "client mode", which I documented in `services/pandanet/client.rb`.
Finally, I noticed that staging has a `PANDANET_USERNAME` set, but production does not.
=> De-skip the pandanet tests

app/controllers/application_controller.rb, app/controllers/content_categories_controller.rb, app/views/content_categories/_form.html.haml, app/views/layouts/_nav.haml, config/locales/en.yml, db/migrate/20210616023945_add_ordinal_and_url_to_content_categories.rb, db/schema.rb
* Ordinal allows content categories to be explicitly ordered by an
admin, rather than just alphabetically by name
* URL allows content category to act as an external link in the nav bar
Closes #214
=> Add ordinal and URL to content categories

app/assets/stylesheets/editable_texts.scss, app/assets/stylesheets/main.scss, app/controllers/content_categories_controller.rb, app/controllers/contents_controller.rb, app/models/content_category.rb, app/views/contents/_form.html.haml, app/views/shared/_md_area.html.haml, db/migrate/20210616193834_add_ordinal_to_contents.rb, db/schema.rb
Allow contents to be ordered within their content category by setting an
ordinal on the individual items.
Also adds a general markdown preview capability to most common markdown
fields to make it easier for admins to see what their markdown will look
like.
=> Add ordinal to contents

app/assets/stylesheets/main.scss, app/views/devise/sessions/new.html.haml
The Sign In Page currently aligns each label to the right. Cleans up Sign In Display.
This change removes that and assures that the password and
text input boxes are the same width.
=> Removed Right Align and Fixed With of Inputs.

app/controllers/reports_controller.rb, app/controllers/rpt/attendee_reports_controller.rb, app/controllers/rpt/attendeeless_user_reports_controller.rb, app/controllers/rpt/cost_summary_reports_controller.rb, app/controllers/rpt/outstanding_balance_reports_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, spec/controllers/users_controller_spec.rb
In every area of the site at present, we only want to show confirmed
users on the UI side. Unconfirmed users, who have not confirmed their
email addresses and cannot, therefore, interact with the site in any way
or be contacted, should be ignored.
=> Only show confirmed users

app/views/registrations/_player_info.html.haml
Resolves #246
-  http://usgo.org/search-ratings now redirects to https://agagd.usgo.org.
=> Changed language to express search-ratings is now the American Go Games Database.

app/models/activity.rb, db/migrate/20210701195219_remove_activities_notes_length_limit.rb, db/schema.rb
The only real reason to have a limit is to keep things that are in the
registration workflow sane for users, but we already cut this
description off in the registration form and offer a "more" button to
link to the full activity. That means the activity really can be as long
as it wants.
This changes the field from a string type (which requires a character
limit) to a text type, which does not.
@see:
https://stackoverflow.com/questions/8694273/changing-a-column-type-to-longer-strings-in-rails
Closes #259
=> Change activity notes field to "text" type without character limit

app/assets/javascripts/application.js, app/assets/javascripts/email_lists.js, app/assets/stylesheets/email_lists.scss, app/assets/stylesheets/main.scss, app/models/attendee.rb, app/views/rpt/tournament_reports/show.html.haml
Also creates a standard "email-list" element that can be used anywhere
that enhances a textarea with separator changer (different clients need
different separators) and a copy-to-clipboard button.
Closes #261
=> Add email lists of registered attendees to tournament reports

app/forms/registration.rb
The definition was changed in 5f1195b0e5b40db45e2d6e69a58570f84684bd41,
which broke two tests, e.g. registrations_controller_spec.rb:73
I believe the change was incorrect, as explained in my comment. So,
this commit reverts that change. This is a *partial* reversion of
5f1195b0e5b40db45e2d6e69a58570f84684bd41. The other parts are not
familiar to me (I don't know what "canceling" an attendee means)
so I left them as is.
=> Fix Registration#attendee_number

db/seeds.rb
Adds `find_or_create_by` to create keys if not a record cannot be found. This will fix the error from `$ rails db:test:prepare`.
```
shell> $ RAILS_ENV=test bin/rails db:seed
rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_years_on_year"
DETAIL:  Key (year)=(2011) already exists.
/home/michael/projects/usgo/development/gocongress-earthschlange/db/seeds.rb:2:in `<main>'
bin/rails:4:in `<main>'
Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_years_on_year"
DETAIL:  Key (year)=(2011) already exists.
/home/michael/projects/usgo/development/gocongress-earthschlange/db/seeds.rb:2:in `<main>'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task …
```
=> Added find_or_create_by to fix RAILS_ENV=test bin/rails db:seed
