usgo/gocongress

app/assets/stylesheets/2018/main.css.scss, app/views/2018/registrations/_personal_info.html.haml, app/views/2018/registrations/_player_info.html.haml, app/views/2018/registrations/_shirt_info.html.haml, app/views/plan_categories/_form.html.haml, app/views/plans/_form.html.haml, app/views/registrations/_form.html.haml
Improve the appearance of various tables.
=> Add styles to make tables look in-theme

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/plan_categories_controller.rb, app/views/plan_categories/_form.html.haml, app/views/plan_categories/show.html.haml, app/views/registrations/_plans.haml, app/views/shared/_md_area.html.haml, db/migrate/20180322102515_add_extended_description_to_plan_categories.rb, db/schema.rb, db/seeds.rb
At the request of Nate Eagle added an extended description attribute to the plan category model.
Also added maxlength attribute to html in order to add counter to text inputs
=> Added extended description to plan categories

app/assets/stylesheets/2018/main.css.scss, db/schema.rb
Worked with Nate Eagle at NGC to remove several display issues
with these fields.  This markup should probably be updated in the
future as the CSS controlling this is overly complicated.
=> Fix display with errors spacing and alignment issues 

app/views/content_categories/show.html.haml, app/views/contents/_form.html.haml
=> Fix select box default

lib/name_inflector.rb
The name_inflector module was not properly dealing with some edge
cases as reflected in some tests I added. Somehow the tests got added to
master and not the refactor I did to pass the tests. This commit fixes
that.
=> Fix name_inflector.rb to capitalize edge cases

app/views/2018/registrations/_player_info.html.haml
It's unfortunate that we don't have official congress email addresses this year, but it can't be helped.
=> Change contact text to direct to contact list

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/exporters/players_xml_exporter.rb, app/models/attendee/who_is_coming.rb, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, config/routes.rb, spec/models/attendee/who_is_coming_spec.rb
On the "Who's coming?" page, the unregistered count (i.e. "Also, X other
people have not finished their registration") is including cancelled
attendees, which it shouldn't.
This adds a test to check for this, then fixes the model.
=> Remove cancelled attendees from unregistered count

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/exporters/players_xml_exporter.rb, app/helpers/attendee_helper.rb, app/models/attendee/who_is_coming.rb, app/views/plan_categories/_plan_table_common_cells.html.haml, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, app/views/shared/_plan_date_fields.haml, config/routes.rb, spec/models/attendee/who_is_coming_spec.rb
* Add labels to text to make it easier to click/select plans
* Improve mini-calendar styling and JS interactions
=> Improve registration table styling

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/exporters/players_xml_exporter.rb, app/helpers/attendee_helper.rb, app/models/attendee/who_is_coming.rb, app/models/attendee/who_is_coming.sql, app/views/plan_categories/_plan_table_common_cells.html.haml, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, app/views/shared/_plan_date_fields.haml, config/routes.rb, spec/factories/attendees.rb, spec/models/attendee/who_is_coming_spec.rb
* Create a failing test for age-based exclusion from who's coming list
* Add age-based check to who's coming sql
Fixes #118
=> Exclude children under 13 from who's coming

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/controllers/years_controller.rb, app/exporters/players_xml_exporter.rb, app/helpers/attendee_helper.rb, app/models/attendee/who_is_coming.rb, app/models/attendee/who_is_coming.sql, app/views/2018/layouts/_footer.haml, app/views/2018/registrations/_player_info.html.haml, app/views/plan_categories/_plan_table_common_cells.html.haml, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, app/views/shared/_plan_date_fields.haml, app/views/users/pay.html.haml, app/views/years/_form.html.haml, config/routes.rb, db/migrate/20180508025356_add_refund_policy_to_year.rb, db/schema.rb, spec/factories/attendees.rb, spec/models/attendee/who_is_coming_spec.rb
I was asked by an attendee if we could make it clearer who users should
contact in case of website issues or questions.
=> Add contact information to footer

app/assets/stylesheets/2018/_variables.scss, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/functions/_decimal-round.scss, app/assets/stylesheets/mixins/_breakpoint.scss, app/controllers/rpt/usopen_players_reports_controller.rb, app/controllers/years_controller.rb, app/exporters/players_xml_exporter.rb, app/helpers/application_helper.rb, app/helpers/attendee_helper.rb, app/models/attendee/who_is_coming.rb, app/models/attendee/who_is_coming.sql, app/views/2018/layouts/_footer.haml, app/views/2018/registrations/_player_info.html.haml, app/views/plan_categories/_plan_table_common_cells.html.haml, app/views/plan_categories/_plan_table_plan_row.html.haml, app/views/reports/index.html.haml, app/views/rpt/usopen_players_reports/show.html.haml, app/views/shared/_plan_date_fields.haml, app/views/users/pay.html.haml, app/views/years/_form.html.haml, config/routes.rb, db/migrate/20180508025356_add_refund_policy_to_year.rb, db/schema.rb, spec/factories/attendees.rb, spec/models/attendee/who_is_coming_spec.rb
Very minor fix to the display of mini calendars in the registration workflow.
=> Mini calendar

app/assets/javascripts/application.js, app/assets/stylesheets/2018/main.css.scss, app/assets/stylesheets/modules/_adaptive-nav.scss, app/views/2018/layouts/_nav.haml, app/views/layouts/_nav.haml
This is a front-end-only PR. 
* Navs display a "more" button if there are more items than can be
displayed on a single line
* Clicking the "more" button reveals the remaining items as a dropdown
Closes #130.
=> Create adaptive navigation to deal with flexible widths

app/assets/stylesheets/2018/main.css.scss, app/views/2018/home/_logo_and_welcome.haml, app/views/registrations/_code_of_conduct.html.haml, app/views/registrations/_form.html.haml
Add to homepage and registration form.
This is a front-end-only PR.
=> Add statement of welcome and AGA CoC

app/assets/stylesheets/2018/main.css.scss, app/controllers/rpt/tshirt_reports_controller.rb, app/views/reports/index.html.haml, app/views/rpt/tshirt_reports/show.html.haml, config/routes.rb, spec/controllers/rpt/tshirt_reports_controller_spec.rb
It's time to finalize the t-shirt order! This creates a simple report
with the size quantities for all active attendees.
=> Create a t-shirt sizes report for ordering

app/assets/javascripts/application.js
We were having a problem where previously set phone values weren't getting properly parsed during initialization. This logic accounts for different possible pre-existing values, and attempts to set the country code intelligently.
Since this is a front-end-only change, I went ahead and pushed it to heroku, @rcristal.
=> Add logic to deal with previously set phone values

app/assets/javascripts/application.js, app/assets/stylesheets/2018/main.css.scss
Creates a daily schedule widget that automatically pages up and down its contents so that it can be displayed on a monitor at Go Congress. Just needs to have "?kiosk" appended to the URL to activate it.
#frontendonly
=> Create a kiosk display for the daily schedule

app/views/attendees/index.html.haml
Update list with spreadsheet data from Lisa.
=> Update "Who is Coming?" List

Gemfile, Gemfile.lock
Updated gemfile to fix some failing rspec tests
=> Update gems that cause rspec test failures

Gemfile, Gemfile.lock, config/environments/production.rb, config/environments/stage.rb
=> Remove asset_sync and use Cloudfront CDN

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature_request.md
Issue templates similar to the Membership Manager style.
=> Adding issue templates

app/forms/registration.rb, app/helpers/application_helper.rb, app/models/attendee.rb, app/models/tournament.rb, app/models/year.rb, app/services/open_graph_data.rb, app/views/2018/layouts/_header.haml, app/views/home/_addresses.haml, app/views/home/_logo_and_welcome.haml, app/views/layouts/_header.haml, app/views/registrations/_contact_info.html.haml, app/views/registrations/_form.html.haml, app/views/registrations/_personal_info.html.haml, app/views/registrations/_plans.haml, app/views/registrations/_wishes.html.haml, lib/concerns/yearly_model.rb, spec/controllers/rpt/transaction_reports_controller_spec.rb, spec/controllers/tournaments_controller_spec.rb, spec/factories/tournaments.rb, spec/factories/years.rb, spec/features/attendee_form_spec.rb, spec/models/attendee_spec.rb, spec/models/tournament_spec.rb, spec/models/year_spec.rb, spec/services/open_graph_data_spec.rb
Closes https://github.com/usgo/gocongress/issues/212
=> Make phone optional

Gemfile, Gemfile.lock, README.md, script/admin_tasks/create_user.rb
=> Add documentation about how to create a local user for development

README.md, script/admin_tasks/create_user.rb
Creates a sigin which uses a local email instead of a usgo.org email to provide users with simpler bootstrap. Additionally adds this development email to development instructions.
- Created Development Admin Email.
- Simplified Sign In instructions.
=> fix user confirmation

app/views/users/_form.html.haml
Resolves #232 by removing bullets from Editing User.
=> Removed bullet from radio button.

Gemfile, Gemfile.lock, README.md, script/admin_tasks/create_user.rb
Make the create_user script interactive to make it easier for developers
to create users without needing to make any modifications to files which
would then show up as changes in their git status.
@EarthSchlange & @jaredbeck:
Thanks a lot, Michael, for your attention to details. You're showing why fresh eyes can be so useful. 😄 
But if we're really going to try to make things easy and discourage any direct editing of files, why not go all the way?
https://user-images.githubusercontent.com/176993/122681729-c7739200-d1c3-11eb-81f5-fce883470c69.mov
=> How to create local user

app/controllers/users_controller.rb, app/views/users/edit.html.haml
=> Added Email for Editing User.

app/views/registrations/aga_member_search.html.haml
Resolves #249.
- Disable Searching... when no input is present.
- Added Error Message for API.
=> add searching message for developers

config/locales/devise.en.yml
=> Added user error message for devise configuration.
